export const jsonCrises = [
  {
    description: "there's a fire",
    score: 100,
    options: [
      {
        description: 'put it out',
        value: 5,
        strength: 10,
        intelligence: 7,
        charisma: 3,
        good: 8,
      },
      {
        description: 'make it bigger',
        value: 5,
        strength: 10,
        intelligence: 5,
        charisma: 2,
        good: -5,
      },
    ],
  },
  {
    description: 'A fight started at the bar',
    score: 100,
    options: [
      {
        description: 'break it up',
        value: 5,
        strength: 10,
        intelligence: 5,
        charisma: 3,
        good: 5,
      },
      {
        description: 'make it bigger',
        value: 5,
        strength: 7,
        intelligence: 3,
        charisma: 5,
        good: -5,
      },
    ],
  },
  {
    description: 'there are monsters running through the town',
    score: 100,
    options: [
      {
        description: 'break it up',
        value: 10,
        strength: 10,
        intelligence: 7,
        charisma: 5,
        good: 10,
      },
      {
        description: 'take a nap',
        value: 5,
        strength: 1,
        intelligence: 1,
        charisma: 1,
        good: -5,
      },
    ],
  },
  {
    description: 'your friends want to write a game in typescript!',
    score: 100,
    options: [
      {
        description: 'happily participate',
        value: 4,
        strength: 2,
        intelligence: 7,
        charisma: 2,
        good: 5,
      },
      {
        description: 'lose sleep',
        value: 2,
        strength: 4,
        intelligence: 4,
        charisma: 2,
        good: 4,
      },
      {
        description: 'go hungry',
        value: 2,
        strength: 5,
        intelligence: 3,
        charisma: 2,
        good: 3,
      },
      {
        description: 'hate life',
        value: 5,
        strength: 2,
        intelligence: 7,
        charisma: 4,
        good: -1,
      },
      {
        description: 'run away as fast as possible',
        value: 10,
        strength: 5,
        intelligence: 8,
        charisma: 3,
        good: 8,
      },
    ],
  },
];
