export const jsonCrises = [
  {
    description: "there's a fire",
    score: 100,
    options: [
      {
        description: 'put it out',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
      {
        description: 'make it bigger',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
    ],
  },
  {
    description: 'A fight started at the bar',
    score: 100,
    options: [
      {
        description: 'break it up',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
      {
        description: 'make it bigger',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
    ],
  },
  {
    description: 'there are monsters running through the town',
    score: 100,
    options: [
      {
        description: 'break it up',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
      {
        description: 'take a nap',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
    ],
  },
  {
    description: 'your friends want to write a game in typescript!',
    score: 100,
    options: [
      {
        description: 'happily participate',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
      {
        description: 'lose sleep',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
      {
        description: 'go hungry',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
      {
        description: 'hate life',
        value: 0,
        strength: 0,
        intelligence: 0,
        charisma: 0,
        good: 0,
      },
      {
        description: 'run away as fast as possible',
        value: 99999999,
        strength: 0,
        intelligence: 999999,
        charisma: 0,
        good: 99999,
      },
    ],
  },
];
